export enum LoadType {
    TRACK_LOADED = "TRACK_LOADED",
    PLAYLIST_LOAD = "PLAYLIST_LOADED",
    SEARCH_RESULT = "SEARCH_RESULT",
    LOAD_FAILED = "LOAD_FAILED",
    NO_RESULTS = "NO_RESULTS",
}
